/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <math.h>


void
calcprog_1( char* host )
{
	CLIENT *clnt;
	double  *result_1;
	double  exp_1_arg;
	double  *result_2;
	double  pi_1_arg = 4;
	double  fx = 0;

	// creating client
	clnt = clnt_create(host, CALCPROG, CALCVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}

	// parsing x
	//printf("Enter x: ");
	scanf ("%lf", &exp_1_arg);
	//printf("%f\n", exp_1_arg);
	exp_1_arg = pow(exp_1_arg, 2) / 2;
	//printf("%f\n", exp_1_arg);
	result_1 = exp_1(&exp_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_2 = pi_1(&pi_1_arg, clnt);
	if (result_2 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	//printf("EXP = %f, PI = %f \n ", *result_1, *result_2);
	fx = (*result_1) / sqrt(2 * (*result_2));
	printf("%f", fx);
	clnt_destroy( clnt );
}


main( int argc, char* argv[] )
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	calcprog_1( host );
}
