/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define CALCPROG ((rpc_uint)0x20000049)
#define CALCVERS ((rpc_uint)1)

#ifdef __cplusplus
#define EXP ((rpc_uint)0)
extern "C" double * exp_1(double *, CLIENT *);
extern "C" double * exp_1_svc(double *, struct svc_req *);
#define PI ((rpc_uint)1)
extern "C" double * pi_1(double *, CLIENT *);
extern "C" double * pi_1_svc(double *, struct svc_req *);

#elif __STDC__
#define EXP ((rpc_uint)0)
extern  double * exp_1(double *, CLIENT *);
extern  double * exp_1_svc(double *, struct svc_req *);
#define PI ((rpc_uint)1)
extern  double * pi_1(double *, CLIENT *);
extern  double * pi_1_svc(double *, struct svc_req *);

#else /* Old Style C */
#define EXP ((rpc_uint)0)
extern  double * exp_1();
extern  double * exp_1_svc();
#define PI ((rpc_uint)1)
extern  double * pi_1();
extern  double * pi_1_svc();
#endif /* Old Style C */

#endif /* !_CALC_H_RPCGEN */
